development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  host: localhost
  database: frab_dev
  pool: 25
  username: frab_dev
  password: kuchkuch

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  host: localhost
  database: frab_prod
  pool: 25
  username: frab_prod
  password: rochelrochel

test: &test
  adapter: mysql2
  encoding: utf8
  reconnect: false
  host: localhost
  database: frab_test
  pool: 25
  username: frab_test
  password: hoesthoest

cucumber:
  <<: *test
